### ISSUE TITLE
React App crash due to unhandled exceeded GitHub API rate limits

### ISSUE THREAD

**Issue by matbun** [dawsonbooth/react-repo-card#12]
First of all, very nice package!
However, it may happen that due to API rate limits you get an empty object instead of a JSON.
With the current code, this causes a crash of the whole app, due to the code at line 127 of index.js:
`backgroundColor: colors[data.language].color, `
where `data` is undefined.  

To solve this issue I had to add a check on the returned object from the API and visualize just the name of the repo (rather than all the infos that are got). I know this is a rough solve, but at least it works smooth.

After line 91 of index.js I added:
```
 if (data.language == undefined){
        // The API erached its limit
        var full_link = "https://github.com/" + username + "/" + repository
        
        return (React.createElement("div", { style: {
            fontFamily: "-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji",
            border: "1px solid #e1e4e8",
            borderRadius: "6px",
            background: "white",
            padding: "16px",
            fontSize: "14px",
            lineHeight: "1.5",
            color: "#24292e"
        } },
        React.createElement("div", { style: { display: "flex", alignItems: "center" } },
            React.createElement("svg", { style: { fill: "#586069", marginRight: "8px" }, viewBox: "0 0 16 16", version: "1.1", width: 16, height: 16, "aria-hidden": "true" },
                React.createElement("path", { fillRule: "evenodd", d: "M2 2.5A2.5 2.5 0 014.5 0h8.75a.75.75 0 01.75.75v12.5a.75.75 0 01-.75.75h-2.5a.75.75 0 110-1.5h1.75v-2h-8a1 1 0 00-.714 1.7.75.75 0 01-1.072 1.05A2.495 2.495 0 012 11.5v-9zm10.5-1V9h-8c-.356 0-.694.074-1 .208V2.5a1 1 0 011-1h8zM5 12.25v3.25a.25.25 0 00.4.2l1.45-1.087a.25.25 0 01.3 0L8.6 15.7a.25.25 0 00.4-.2v-3.25a.25.25 0 00-.25-.25h-3.5a.25.25 0 00-.25.25z" })),
            React.createElement("span", { style: { fontWeight: 600, color: "#0366d6" } },
                React.createElement("a", { style: { textDecoration: "none", color: "inherit" }, href: full_link }, repository)))));
    }
```

This can indeed be improved / prettified.

Another very small note on improving UX: I think that opening the repo we page in a new tab is better than in the same tab of the website, so that you don't temporarily lose the page.
To achieve this I also added `target: "_blank"` property to `a` elements, for instance:
`React.createElement("a", { style: { textDecoration: "none", color: "inherit" }, href: data.html_url , target: "_blank"}, data.name)`

Looking forward for the next release! ;)

**Comment by dawsonbooth** [comment]
Added in v1.2.0 👍 

Thanks for the issue! Feel free to submit a PR next time you want to make any changes to code :)
