### ISSUE TITLE
Requesting for package update

### ISSUE THREAD

**Issue by Monochromish** [dawsonbooth/react-repo-card#26]
There have been a few updates, mostly related to the `Dark Theme` which I wanted to use on my site, though the package's last update was over 2 months ago.

Requesting you for a package update.

Thank you!

**Comment by dawsonbooth** [comment]
I'll try to publish an update as soon as I find the time!

In the meantime, you can always add a package directly from a git repo directly: https://stackoverflow.com/questions/43411864/how-to-install-package-from-github-repo-in-yarn#43636577

**Comment by Monochromish** [comment]
Alright thanks!

**Comment by dawsonbooth** [comment]
[v2.0.0](https://www.npmjs.com/package/react-repo-card) is up! Let me know if you run into any problems :)
