### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by MehmetBozkir** [dawsonbooth/react-repo-card#34]
[gg](https://dawsonbooth.github.io/react-repo-card/?path=/story/example--example)

hello buddy, your link is blown. i think the link here is ok => [new](https://dawsonbooth.github.io/react-repo-card/?path=/story/example--examplel)

**Comment by dawsonbooth** [comment]
Ah, thanks! Been meaning to address this for all my repos.

This link should work fine (i.e. replace `dawsonbooth.com` with `dawsonbooth.github.io`): https://dawsonbooth.github.io/react-repo-card/

**Comment by MehmetBozkir** [comment]
yes it works smoothly, nice to meet you. good work :)
