### ISSUE TITLE
NPM package is missing scripts

### ISSUE THREAD

**Issue by SamKirkland** [dawsonbooth/react-repo-card#4]
Currently the NPM package only includes `LICENSE`, `package.json`, and `README.md`
But the actual tsc output (dist/index.js) is missing.

No rush on this from my side, I'll be copying the component inline 👍 

Thanks for making this react version of Tarptaeya's plugin.

**Comment by dawsonbooth** [comment]
Wow, thanks for letting me know. It's weird how much traffic this package got without actually working at all!

This should be fixed in v[1.0.2](https://www.npmjs.com/package/react-repo-card). Let me know if you have any more problems!

**Comment by SamKirkland** [comment]
Thanks!
